# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: |
          pip install cython
          python setup.py build_ext --inplace
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: nmake
        shell: cmd
        run: |
          nmake -f Makefile.githubactions
      - name: package
        shell: pwsh
        run: |
          & scripts\windows-publish.ps1
      - uses: actions/upload-artifact@v2
        with:
          name: "spider"
          path: "spider.zip"
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: spider.zip
          asset_name: spider.zip
          tag: ${{ github.ref }}
          overwrite: true 
          body: "This is auto-generated by Github Actions."
